[2024-11-09 05:10:48,343 GMT] INFO::trigger_reload() C:\PythonProjects\emc_test_automation_dashboard\emc_test_automation_api\src\services\image_ops.py changed, reloading.
[2024-11-09 05:11:19,654 GMT] INFO::trigger_reload() C:\PythonProjects\emc_test_automation_dashboard\emc_test_automation_api\src\services\image_ops.py changed, reloading.
[2024-11-09 05:15:25,095 GMT] INFO::trigger_reload() C:\PythonProjects\emc_test_automation_dashboard\emc_test_automation_api\src\services\image_ops.py changed, reloading.
[2024-11-09 05:16:03,874 GMT] INFO::trigger_reload() C:\PythonProjects\emc_test_automation_dashboard\emc_test_automation_api\src\services\image_ops.py changed, reloading.
[2024-11-09 05:17:30,978 GMT] INFO::trigger_reload() C:\PythonProjects\emc_test_automation_dashboard\emc_test_automation_api\src\services\image_ops.py changed, reloading.
[2024-11-09 05:18:33,816 GMT] INFO::trigger_reload() C:\PythonProjects\emc_test_automation_dashboard\emc_test_automation_api\src\services\image_ops.py changed, reloading.
[2024-11-09 05:19:10,047 GMT] INFO::trigger_reload() C:\PythonProjects\emc_test_automation_dashboard\emc_test_automation_api\src\services\image_ops.py changed, reloading.
[2024-11-09 05:19:31,861 GMT] INFO::trigger_reload() C:\PythonProjects\emc_test_automation_dashboard\emc_test_automation_api\src\services\image_ops.py changed, reloading.
[2024-11-09 05:20:17,633 GMT] INFO::trigger_reload() C:\PythonProjects\emc_test_automation_dashboard\emc_test_automation_api\src\services\image_ops.py changed, reloading.
[2024-11-09 05:20:50,850 GMT] INFO::trigger_reload() C:\PythonProjects\emc_test_automation_dashboard\emc_test_automation_api\src\services\image_ops.py changed, reloading.
[2024-11-09 05:22:33,531 GMT] INFO::trigger_reload() C:\PythonProjects\emc_test_automation_dashboard\emc_test_automation_api\src\services\image_ops.py changed, reloading.
[2024-11-09 05:23:14,573 GMT] INFO::trigger_reload() C:\PythonProjects\emc_test_automation_dashboard\emc_test_automation_api\src\services\image_ops.py changed, reloading.
[2024-11-09 05:26:45,671 GMT] INFO::trigger_reload() C:\PythonProjects\emc_test_automation_dashboard\emc_test_automation_api\src\services\image_ops.py changed, reloading.
[2024-11-09 05:27:08,268 GMT] INFO::trigger_reload() C:\PythonProjects\emc_test_automation_dashboard\emc_test_automation_api\src\services\image_ops.py changed, reloading.
[2024-11-09 05:29:41,545 GMT] INFO::trigger_reload() C:\PythonProjects\emc_test_automation_dashboard\emc_test_automation_api\src\services\image_ops.py changed, reloading.
[2024-11-09 05:30:08,382 GMT] INFO::trigger_reload() C:\PythonProjects\emc_test_automation_dashboard\emc_test_automation_api\src\services\image_ops.py changed, reloading.
[2024-11-09 05:30:30,647 GMT] INFO::trigger_reload() C:\PythonProjects\emc_test_automation_dashboard\emc_test_automation_api\src\services\image_ops.py changed, reloading.
[2024-11-09 05:33:54,133 GMT] INFO::trigger_reload() C:\PythonProjects\emc_test_automation_dashboard\emc_test_automation_api\src\services\image_ops.py changed, reloading.
[2024-11-09 05:34:20,160 GMT] INFO::trigger_reload() C:\PythonProjects\emc_test_automation_dashboard\emc_test_automation_api\src\services\image_ops.py changed, reloading.
[2024-11-09 05:34:40,730 GMT] INFO::trigger_reload() C:\PythonProjects\emc_test_automation_dashboard\emc_test_automation_api\src\services\image_ops.py changed, reloading.
[2024-11-09 05:34:59,703 GMT] INFO::trigger_reload() C:\PythonProjects\emc_test_automation_dashboard\emc_test_automation_api\src\services\image_ops.py changed, reloading.
[2024-11-09 05:35:08,481 GMT] ERROR::log_response() Internal Server Error: /generate_schematic_image/
Traceback (most recent call last):
  File "C:\Users\saldanha\miniconda3\envs\emc_test_automation_dashboard\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\saldanha\miniconda3\envs\emc_test_automation_dashboard\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\PythonProjects\emc_test_automation_dashboard\emc_test_automation_gui\views.py", line 95, in generate_schematic_image
    file_data = png_file_path[0]['image']
KeyError: 'image'
[2024-11-09 05:35:21,931 GMT] ERROR::log_response() Internal Server Error: /generate_schematic_image/
Traceback (most recent call last):
  File "C:\Users\saldanha\miniconda3\envs\emc_test_automation_dashboard\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\saldanha\miniconda3\envs\emc_test_automation_dashboard\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\PythonProjects\emc_test_automation_dashboard\emc_test_automation_gui\views.py", line 95, in generate_schematic_image
    file_data = png_file_path[0]['image']
KeyError: 'image'
[2024-11-09 05:35:35,965 GMT] INFO::trigger_reload() C:\PythonProjects\emc_test_automation_dashboard\emc_test_automation_api\src\services\image_ops.py changed, reloading.
[2024-11-09 05:35:46,434 GMT] ERROR::log_response() Internal Server Error: /generate_schematic_image/
Traceback (most recent call last):
  File "C:\Users\saldanha\miniconda3\envs\emc_test_automation_dashboard\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\saldanha\miniconda3\envs\emc_test_automation_dashboard\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\PythonProjects\emc_test_automation_dashboard\emc_test_automation_gui\views.py", line 95, in generate_schematic_image
    file_data = png_file_path[0]['image']
KeyError: 'image'
[2024-11-09 05:35:52,084 GMT] INFO::trigger_reload() C:\PythonProjects\emc_test_automation_dashboard\emc_test_automation_api\src\services\image_ops.py changed, reloading.
[2024-11-09 05:36:20,601 GMT] INFO::trigger_reload() C:\PythonProjects\emc_test_automation_dashboard\emc_test_automation_api\src\services\image_ops.py changed, reloading.
[2024-11-09 05:36:47,895 GMT] INFO::trigger_reload() C:\PythonProjects\emc_test_automation_dashboard\emc_test_automation_api\src\services\image_ops.py changed, reloading.
[2024-11-09 05:37:09,823 GMT] INFO::trigger_reload() C:\PythonProjects\emc_test_automation_dashboard\emc_test_automation_api\src\services\image_ops.py changed, reloading.
[2024-11-09 05:37:19,581 GMT] ERROR::log_response() Internal Server Error: /generate_schematic_image/
Traceback (most recent call last):
  File "C:\Users\saldanha\miniconda3\envs\emc_test_automation_dashboard\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\saldanha\miniconda3\envs\emc_test_automation_dashboard\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\PythonProjects\emc_test_automation_dashboard\emc_test_automation_gui\views.py", line 95, in generate_schematic_image
    file_data = png_file_path[0]['image']
KeyError: 'image'
[2024-11-09 05:37:33,302 GMT] INFO::trigger_reload() C:\PythonProjects\emc_test_automation_dashboard\emc_test_automation_api\src\services\image_ops.py changed, reloading.
[2024-11-09 05:37:58,798 GMT] INFO::trigger_reload() C:\PythonProjects\emc_test_automation_dashboard\emc_test_automation_api\src\services\image_ops.py changed, reloading.
[2024-11-09 05:38:30,412 GMT] INFO::trigger_reload() C:\PythonProjects\emc_test_automation_dashboard\emc_test_automation_api\src\services\image_ops.py changed, reloading.
[2024-11-09 05:38:40,062 GMT] ERROR::log_response() Internal Server Error: /generate_schematic_image/
Traceback (most recent call last):
  File "C:\Users\saldanha\miniconda3\envs\emc_test_automation_dashboard\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\saldanha\miniconda3\envs\emc_test_automation_dashboard\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\PythonProjects\emc_test_automation_dashboard\emc_test_automation_gui\views.py", line 95, in generate_schematic_image
    file_data = png_file_path[0]['image']
KeyError: 'image'
[2024-11-09 05:39:18,182 GMT] INFO::trigger_reload() C:\PythonProjects\emc_test_automation_dashboard\emc_test_automation_api\src\services\image_ops.py changed, reloading.
[2024-11-09 05:40:10,687 GMT] INFO::trigger_reload() C:\PythonProjects\emc_test_automation_dashboard\emc_test_automation_api\src\services\image_ops.py changed, reloading.
[2024-11-09 05:40:35,890 GMT] INFO::trigger_reload() C:\PythonProjects\emc_test_automation_dashboard\emc_test_automation_api\src\services\image_ops.py changed, reloading.
[2024-11-09 05:40:59,080 GMT] INFO::trigger_reload() C:\PythonProjects\emc_test_automation_dashboard\emc_test_automation_api\src\services\image_ops.py changed, reloading.
[2024-11-09 05:41:29,699 GMT] INFO::trigger_reload() C:\PythonProjects\emc_test_automation_dashboard\emc_test_automation_api\src\services\image_ops.py changed, reloading.
[2024-11-09 05:41:58,649 GMT] INFO::trigger_reload() C:\PythonProjects\emc_test_automation_dashboard\emc_test_automation_api\src\services\image_ops.py changed, reloading.
[2024-11-09 05:42:36,302 GMT] INFO::trigger_reload() C:\PythonProjects\emc_test_automation_dashboard\emc_test_automation_api\src\services\image_ops.py changed, reloading.
[2024-11-09 05:43:12,157 GMT] INFO::trigger_reload() C:\PythonProjects\emc_test_automation_dashboard\emc_test_automation_api\src\services\image_ops.py changed, reloading.
[2024-11-09 05:47:21,721 GMT] INFO::trigger_reload() C:\PythonProjects\emc_test_automation_dashboard\emc_test_automation_api\src\services\image_ops.py changed, reloading.
[2024-11-09 05:53:30,910 GMT] INFO::trigger_reload() C:\PythonProjects\emc_test_automation_dashboard\emc_test_automation_api\src\services\image_ops.py changed, reloading.
[2024-11-09 05:53:40,815 GMT] ERROR::log_response() Internal Server Error: /generate_schematic_image/
Traceback (most recent call last):
  File "C:\Users\saldanha\miniconda3\envs\emc_test_automation_dashboard\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\saldanha\miniconda3\envs\emc_test_automation_dashboard\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\PythonProjects\emc_test_automation_dashboard\emc_test_automation_gui\views.py", line 95, in generate_schematic_image
    file_data = png_file_path[0]['image']
KeyError: 'image'
[2024-11-09 05:55:10,182 GMT] ERROR::log_response() Internal Server Error: /generate_schematic_image/
Traceback (most recent call last):
  File "C:\Users\saldanha\miniconda3\envs\emc_test_automation_dashboard\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\saldanha\miniconda3\envs\emc_test_automation_dashboard\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\PythonProjects\emc_test_automation_dashboard\emc_test_automation_gui\views.py", line 95, in generate_schematic_image
    file_data = png_file_path[0]['image']
KeyError: 'image'
[2024-11-09 05:57:25,172 GMT] INFO::trigger_reload() C:\PythonProjects\emc_test_automation_dashboard\emc_test_automation_api\src\services\image_ops.py changed, reloading.
[2024-11-09 06:00:18,083 GMT] INFO::trigger_reload() C:\PythonProjects\emc_test_automation_dashboard\emc_test_automation_api\src\services\image_ops.py changed, reloading.
[2024-11-09 06:03:14,921 GMT] INFO::trigger_reload() C:\PythonProjects\emc_test_automation_dashboard\emc_test_automation_api\src\services\image_ops.py changed, reloading.
[2024-11-09 06:07:14,404 GMT] INFO::trigger_reload() C:\PythonProjects\emc_test_automation_dashboard\emc_test_automation_api\src\services\image_ops.py changed, reloading.
[2024-11-09 06:07:28,226 GMT] ERROR::log_response() Internal Server Error: /generate_schematic_image/
Traceback (most recent call last):
  File "C:\Users\saldanha\miniconda3\envs\emc_test_automation_dashboard\lib\site-packages\django\utils\datastructures.py", line 84, in __getitem__
    list_ = super().__getitem__(key)
KeyError: 'file1'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\saldanha\miniconda3\envs\emc_test_automation_dashboard\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\saldanha\miniconda3\envs\emc_test_automation_dashboard\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\PythonProjects\emc_test_automation_dashboard\emc_test_automation_gui\views.py", line 73, in generate_schematic_image
    if request.method == 'POST' and request.FILES['file1']:
  File "C:\Users\saldanha\miniconda3\envs\emc_test_automation_dashboard\lib\site-packages\django\utils\datastructures.py", line 86, in __getitem__
    raise MultiValueDictKeyError(key)
django.utils.datastructures.MultiValueDictKeyError: 'file1'
[2024-11-09 09:25:37,918 GMT] INFO::trigger_reload() C:\PythonProjects\emc_test_automation_dashboard\emc_test_automation_api\src\services\image_ops.py changed, reloading.
